name: Build Android 16 APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Force Gradle Wrapper Injection
        run: |
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew

      - name: Build Production Debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartWallpaper-v1-APK
          path: "**/outputs/**/*.apk"
          if-no-files-found: error
